// Central export point for all types

// Re-export base types
export * from "./base.types";

// Re-export specific domain types
export * from "./campaign.types";
export * from "./credentials.types";
export * from "./sync.types";

// Re-export database types (generated by Supabase)
export type { Database, Tables, Enums } from "./supabase.types";

// Re-export user and auth types
export * from "./auth.types";
export * from "./user";

// Re-export specific database types
export type { UserRole, TeamMember, TeamInvitation } from "./database.types";

// Re-export dashboard types
export * from "./dashboard";

// Re-export google ads types (excluding conflicting types)
export type {
  GoogleAdsCredentials,
  GoogleAdsCredentials as GoogleAdsApiCredentials,
  GoogleAdsAccount,
  GoogleAdsCampaign,
  GoogleAdsMetrics,
  CampaignStatusUpdate,
  GoogleAdsLabel,
  CampaignLabelAssignment,
  SyncConfig,
  SyncError,
  GoogleAdsQuery,
  GoogleAdsApiResponse,
  GoogleAdsError,
  BatchOperation,
  ReportQuery,
  CampaignBudget,
  ChangeEvent,
  QueueJob,
  SchedulerConfig,
  // Rename SyncResult to avoid conflict
  SyncResult as GoogleAdsSyncResult,
} from "./google-ads.types";

// Re-export platform types
export * from "./platform";

// Type utilities for database <-> application layer conversion
export * from "./type-utils";
